# Generated by Django 5.2.4 on 2025-08-15 14:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del Proyecto')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FeatureSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('features', models.JSONField(default=list)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_sets', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nombre de la Fuente de Datos')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('file', models.FileField(blank=True, null=True, upload_to='datasources/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('data_type', models.CharField(choices=[('ORIGINAL', 'Original'), ('PREPARED', 'Preparado'), ('FUSED', 'Fusionado')], default='ORIGINAL', max_length=10, verbose_name='Tipo de Dato')),
                ('is_derived', models.BooleanField(default=False, help_text='True si esta es una fuente de datos derivada.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parents', models.ManyToManyField(blank=True, related_name='children', to='projects.datasource', verbose_name='Fuentes de Datos de Origen (Padres)')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasources', to='projects.project')),
            ],
            options={
                'verbose_name': 'Fuente de Datos',
                'verbose_name_plural': 'Fuentes de Datos',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Transformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(help_text='The execution order of the transformation.')),
                ('operation_type', models.CharField(help_text="The type of transformation operation (e.g., 'select_columns', 'filter_rows', 'merge').", max_length=50)),
                ('parameters', models.JSONField(help_text="Arguments for the transformation operation (e.g., {'columns': ['col1', 'col2']}).")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('derived_datasource', models.ForeignKey(help_text='The derived data source resulting from this transformation.', on_delete=django.db.models.deletion.CASCADE, related_name='transformations', to='projects.datasource')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('derived_datasource', 'order')},
            },
        ),
    ]
