# Generated by Django 5.2.4 on 2025-08-11 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='data_type',
            field=models.CharField(choices=[('ORIGINAL', 'Original'), ('PREPARED', 'Preparado'), ('FUSED', 'Fusionado')], default='ORIGINAL', max_length=10),
        ),
        migrations.AddField(
            model_name='datasource',
            name='parents',
            field=models.ManyToManyField(blank=True, related_name='children', to='projects.datasource'),
        ),
    ]
