# Generated by Django 5.2.4 on 2025-08-15 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='quality_report',
            field=models.JSONField(blank=True, help_text='Stores the data quality analysis results.', null=True),
        ),
        migrations.AddField(
            model_name='datasource',
            name='status',
            field=models.CharField(choices=[('UPLOADING', 'Subiendo'), ('PROCESSING', 'Procesando'), ('READY', 'Listo'), ('ERROR', 'Error')], default='UPLOADING', max_length=20),
        ),
    ]
