# Generated by Django 5.2.4 on 2025-08-16 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_datasource_quality_report_datasource_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='quality_report_path',
            field=models.CharField(blank=True, help_text='Path to the Great Expectations HTML quality report', max_length=500, null=True),
        ),
    ]
