# Generated by Django 5.2.4 on 2025-08-16 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_datasource_quality_report_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Permite que otros usuarios vean este proyecto', verbose_name='Proyecto Público'),
        ),
    ]
