# Generated by Django 5.2.4 on 2025-08-16 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='recipe_steps',
            field=models.JSONField(blank=True, default=list, help_text='Lista de pasos de transformación aplicados a esta fuente de datos'),
        ),
    ]
