# Generated by Django 5.2.4 on 2025-08-17 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_datasource_recipe_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='missing_data_report',
            field=models.JSONField(blank=True, help_text='Stores deep missing data analysis results including feature importance and combination counts', null=True),
        ),
    ]
