# Generated by Django 5.2.4 on 2025-08-17 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_datasource_missing_data_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_favorite',
            field=models.BooleanField(default=False, help_text='Marca este proyecto como favorito para el usuario', verbose_name='Proyecto Favorito'),
        ),
    ]
