# Generated by Django 5.2.4 on 2025-08-18 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_refactor_datasource_to_many_to_many'),
        ('projects', '0009_add_many_to_many'),
    ]

    operations = [
    ]
