# Generated by Django 5.2.4 on 2025-08-19 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_merge_20250818_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='column_flags',
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Flags de calidad por columna para validaciones ML',
                null=True
            ),
        ),
    ]
