# Generated by Django 5.2.4 on 2025-08-16 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HyperparameterPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the hyperparameter preset', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of what this preset is for')),
                ('hyperparameters', models.JSONField(help_text='JSON object containing hyperparameter names and values')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User who owns this preset', on_delete=django.db.models.deletion.CASCADE, related_name='hyperparameter_presets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hyperparameter Preset',
                'verbose_name_plural': 'Hyperparameter Presets',
                'ordering': ['-updated_at', 'name'],
                'unique_together': {('name', 'user')},
            },
        ),
    ]
