# Generated by Django 5.2.4 on 2025-08-15 15:28

import connectors.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Un nombre descriptivo para esta conexión.', max_length=100)),
                ('database_type', models.CharField(choices=[('POSTGRESQL', 'PostgreSQL'), ('MYSQL', 'MySQL'), ('SQLITE', 'SQLite')], max_length=20)),
                ('host', models.CharField(max_length=100)),
                ('port', models.PositiveIntegerField()),
                ('database_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('password', connectors.fields.EncryptedCharField(max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='database_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'name')},
            },
        ),
    ]
