# Generated by Django 5.2.4 on 2025-08-17 04:00

import connectors.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='databaseconnection',
            options={'ordering': ['-created_at'], 'verbose_name': 'Database Connection', 'verbose_name_plural': 'Database Connections'},
        ),
        migrations.AlterUniqueTogether(
            name='databaseconnection',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='databaseconnection',
            name='database_name',
            field=models.CharField(help_text='Name of the database', max_length=255),
        ),
        migrations.AlterField(
            model_name='databaseconnection',
            name='database_type',
            field=models.CharField(choices=[('postgresql', 'PostgreSQL'), ('mysql', 'MySQL'), ('sqlite', 'SQLite')], max_length=20),
        ),
        migrations.AlterField(
            model_name='databaseconnection',
            name='host',
            field=models.CharField(blank=True, help_text='Database host (not required for SQLite)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='databaseconnection',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='databaseconnection',
            name='name',
            field=models.CharField(help_text='Friendly name for this connection', max_length=255),
        ),
        migrations.AlterField(
            model_name='databaseconnection',
            name='password',
            field=connectors.fields.EncryptedCharField(blank=True, help_text='Database password (encrypted)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='databaseconnection',
            name='port',
            field=models.PositiveIntegerField(blank=True, help_text='Database port (not required for SQLite)', null=True),
        ),
        migrations.AlterField(
            model_name='databaseconnection',
            name='username',
            field=models.CharField(blank=True, help_text='Database username (not required for SQLite)', max_length=255, null=True),
        ),
    ]
