"""
Django settings for hydroML project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import warnings
from pathlib import Path
import dj_database_url
from dotenv import load_dotenv
import sentry_sdk
from sentry_sdk.integrations.django import DjangoIntegration
from sentry_sdk.integrations.celery import CeleryIntegration

# Configure Plotly as primary graphics library for web applications
# Plotly is optimized for web, interactive, and Docker environments
try:
    from core.plotly_config import configure_plotly
    configure_plotly()
except ImportError:
    # Fallback configuration if core.plotly_config is not available
    import plotly.io as pio
    pio.templates.default = "plotly_white"

# Configure warning filters to suppress known deprecation warnings from third-party libraries
warnings.filterwarnings(
    'ignore',
    category=DeprecationWarning,
    message=r'.*PydanticDeprecatedSince20.*',
    module=r'pydantic.*'
)
warnings.filterwarnings(
    'ignore', 
    category=DeprecationWarning,
    message=r'.*np\.inexact.*',
    module=r'numpy.*'
)
warnings.filterwarnings(
    'ignore',
    category=DeprecationWarning, 
    message=r'.*np\.integer.*',
    module=r'numpy.*'
)
warnings.filterwarnings(
    'ignore',
    category=DeprecationWarning,
    message=r'.*np\.generic.*', 
    module=r'numpy.*'
)
warnings.filterwarnings(
    'ignore',
    category=DeprecationWarning,
    message=r'.*@validator.*field_validator.*',
    module=r'.*'
)
warnings.filterwarnings(
    'ignore',
    category=DeprecationWarning,
    message=r'.*SHAP.*',
    module=r'shap.*'
)


# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "default-unsafe-key")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "True") == "True"

ALLOWED_HOSTS = os.getenv("DJANGO_ALLOWED_HOSTS", "127.0.0.1,localhost").split(",")


# Application definition

INSTALLED_APPS = [
    # Django Core Apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # --- NUESTRAS APPS REFACTORIZADAS ---
    'core.apps.CoreConfig',
    'projects.apps.ProjectsConfig',
    'data_tools.apps.DataToolsConfig',
    'experiments.apps.ExperimentsConfig',
    'accounts.apps.AccountsConfig',
    'connectors.apps.ConnectorsConfig',
]

# Añadir a INSTALLED_APPS
INSTALLED_APPS += [
    'crispy_forms',
    'crispy_tailwind',
    'taggit',
]

TAILWIND_APP_NAME = 'core'


# Necesario para el refresco automático del navegador
INTERNAL_IPS = [
    "127.0.0.1",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "hydroML.urls"

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # Custom context processors for navigation
                'core.context_processors.navigation_context',
                'core.context_processors.breadcrumb_context',
                'core.context_processors.navigation_counts',
                'core.context_processors.sentry_dsn',
            ],
        },
    },
]

WSGI_APPLICATION = "hydroML.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('POSTGRES_NAME'),
        'USER': os.environ.get('POSTGRES_USER'),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD'),
        'HOST': os.environ.get('POSTGRES_HOST'),
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# --- AÑADE ESTA CONFIGURACIÓN ---
# Esta configuración le dice a Django cómo encontrar archivos estáticos.
# AppDirectoriesFinder es crucial para que encuentre los archivos dentro de cada app.
STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder', # Busca en STATICFILES_DIRS
    'django.contrib.staticfiles.finders.AppDirectoriesFinder', # Busca en el directorio 'static' de cada app
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# En HydroML/settings.py (al final)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# --- CELERY SETTINGS ---
# Lee el host de Redis desde las variables de entorno (para Docker).
# Si no la encuentra, usa 'localhost' por defecto (para desarrollo local).
REDIS_HOST = os.environ.get('REDIS_HOST', 'localhost')

CELERY_BROKER_URL = f'redis://{REDIS_HOST}:6379/0'
CELERY_RESULT_BACKEND = f'redis://{REDIS_HOST}:6379/0'

CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'

LOGIN_REDIRECT_URL = '/projects/'
LOGOUT_REDIRECT_URL = '/accounts/login/'

# Security settings for production
if not DEBUG:
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_SSL_REDIRECT = os.getenv('SECURE_SSL_REDIRECT', 'False') == 'True'



# Configuración de Sentry (unificada)
SENTRY_DSN = os.getenv("SENTRY_DSN", None)
# Initialize Sentry only when a DSN is provided. In development you may want
# to set traces_sample_rate=1.0 for full performance traces; here we use
# 1.0 for development when DEBUG is True and still allow configuration by env.
if SENTRY_DSN:
    sentry_sdk.init(
        dsn=SENTRY_DSN,
        integrations=[DjangoIntegration(), CeleryIntegration()],
        # Enable performance monitoring
        traces_sample_rate=float(os.getenv('SENTRY_TRACES_SAMPLE_RATE', '1.0')),
        # Send PII (useful for debugging, ensure policy compliance in prod)
        send_default_pii=True,
        # Respect environment
        environment=os.getenv('SENTRY_ENVIRONMENT', 'development' if DEBUG else 'production'),
    )

# --- Configuración de Crispy Forms ---
CRISPY_ALLOWED_TEMPLATE_PACKS = "tailwind"
CRISPY_TEMPLATE_PACK = "tailwind"

# Configuración de claves para la encriptación
FERNET_KEYS = [
    os.getenv('DJANGO_FERNET_KEY')
]