# Generated by Django 5.2.4 on 2025-08-15 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_datasource_quality_report_datasource_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(default='fusion', max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('IN_PROGRESS', 'En Progreso'), ('SUCCESS', 'Completada'), ('FAILURE', 'Fallida')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('input_datasources', models.ManyToManyField(related_name='processing_tasks_as_input', to='projects.datasource')),
                ('output_datasource', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generating_task', to='projects.datasource')),
            ],
        ),
    ]
