# Generated by Django 5.2.4 on 2025-08-17 07:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_tools', '0001_initial'),
        ('projects', '0006_datasource_missing_data_report'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the query history entry', primary_key=True, serialize=False)),
                ('sql_query', models.TextField(help_text='The SQL query that was executed')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When the query was executed')),
                ('rows_returned', models.PositiveIntegerField(blank=True, help_text='Number of rows returned by the query', null=True)),
                ('execution_time_ms', models.PositiveIntegerField(blank=True, help_text='Query execution time in milliseconds', null=True)),
                ('was_successful', models.BooleanField(default=True, help_text='Whether the query executed successfully')),
                ('datasource', models.ForeignKey(help_text='DataSource the query was executed against', on_delete=django.db.models.deletion.CASCADE, related_name='query_history', to='projects.datasource')),
                ('user', models.ForeignKey(help_text='User who executed the query', on_delete=django.db.models.deletion.CASCADE, related_name='sql_query_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Query History',
                'verbose_name_plural': 'Query Histories',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'datasource', '-timestamp'], name='data_tools__user_id_c1ba79_idx'), models.Index(fields=['user', '-timestamp'], name='data_tools__user_id_eef865_idx')],
            },
        ),
    ]
