# Generated by Django 5.2.4 on 2025-08-20 13:21

import uuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_tools', '0002_queryhistory'),
        ('projects', '0006_datasource_missing_data_report'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the export job', primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', help_text='Current status of the export job', max_length=20)),
                ('format', models.CharField(choices=[('csv', 'CSV'), ('json', 'JSON'), ('parquet', 'Parquet'), ('excel', 'Excel')], help_text='Export format for the data', max_length=10)),
                ('filters', models.JSONField(blank=True, default=dict, help_text='Applied filters for the export (SQL conditions, column selections, etc.)')),
                ('progress', models.IntegerField(default=0, help_text='Export progress as percentage (0-100)')),
                ('file_path', models.CharField(blank=True, help_text='Path to the generated export file', max_length=500)),
                ('file_size', models.BigIntegerField(blank=True, help_text='Size of the generated file in bytes', null=True)),
                ('row_count', models.IntegerField(blank=True, help_text='Number of rows in the exported data', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if the export failed')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the export job was created')),
                ('started_at', models.DateTimeField(blank=True, help_text='When the export job started processing', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the export job completed (successfully or with failure)', null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When the export file will be automatically deleted', null=True)),
                ('datasource', models.ForeignKey(help_text='DataSource to be exported', on_delete=django.db.models.deletion.CASCADE, related_name='export_jobs', to='projects.datasource')),
                ('user', models.ForeignKey(help_text='User who initiated the export job', on_delete=django.db.models.deletion.CASCADE, related_name='export_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Export Job',
                'verbose_name_plural': 'Export Jobs',
                'db_table': 'data_tools_export_job',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExportTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the export template', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Descriptive name for the export template', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional description of what this template does')),
                ('template_type', models.CharField(choices=[('user', 'User Template'), ('system', 'System Template'), ('shared', 'Shared Template')], default='user', help_text='Type of template (user, system, or shared)', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this template is active and available for use')),
                ('configuration', models.JSONField(help_text='Template configuration including format, filters, and export settings')),
                ('usage_count', models.IntegerField(default=0, help_text='Number of times this template has been used')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the template was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the template was last updated')),
                ('last_used_at', models.DateTimeField(blank=True, help_text='When the template was last used for an export', null=True)),
                ('user', models.ForeignKey(help_text='User who created this template', on_delete=django.db.models.deletion.CASCADE, related_name='export_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Export Template',
                'verbose_name_plural': 'Export Templates',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='exportjob',
            index=models.Index(fields=['user', '-created_at'], name='data_tools__user_id_a1b2c3_idx'),
        ),
        migrations.AddIndex(
            model_name='exportjob',
            index=models.Index(fields=['status', '-created_at'], name='data_tools__status_c4d5e6_idx'),
        ),
        migrations.AddIndex(
            model_name='exportjob',
            index=models.Index(fields=['datasource', '-created_at'], name='data_tools__datasou_f7g8h9_idx'),
        ),
        migrations.AddIndex(
            model_name='exportjob',
            index=models.Index(fields=['expires_at'], name='data_tools__expires_i0j1k2_idx'),
        ),
        migrations.AddIndex(
            model_name='exporttemplate',
            index=models.Index(fields=['user', 'template_type', '-updated_at'], name='data_tools__user_id_l3m4n5_idx'),
        ),
        migrations.AddIndex(
            model_name='exporttemplate',
            index=models.Index(fields=['template_type', 'is_active'], name='data_tools__templat_o6p7q8_idx'),
        ),
        migrations.AddIndex(
            model_name='exporttemplate',
            index=models.Index(fields=['usage_count', '-last_used_at'], name='data_tools__usage_c_r9s0t1_idx'),
        ),
        migrations.AddConstraint(
            model_name='exporttemplate',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_template_name_per_user'),
        ),
    ]
